{
  codecov: { strict_yaml_branch: main },
  coverage:
    {
      status:
        {
          patch: { default: { target: 100%, threshold: 0%, only_pulls: true } },
          project: { default: { target: 100%, threshold: 0% } },
        },
    },
  comment: { layout: 'diff, files', behavior: new },
}
