{
  version: 2,
  updates:
    [
      {
        package-ecosystem: npm,
        directory: '/',
        schedule: { interval: daily },
        open-pull-requests-limit: 1,
        commit-message: { prefix: env },
        rebase-strategy: disabled,
        versioning-strategy: increase,
        labels: [by-dependabot, node-dependencies],
      },
    ],
}
