titleOnly: true
allowMergeCommits: true
types:
  - chore
  - devops
  - docs
  - env
  - feat
  - fix
  - lint
  - perf
  - refactor
  - repo
  - revert
  - style
  - test
scopes:
  - core
  - protocol-http
  - protocol-tcp
