titleOnly: true
allowMergeCommits: true
types:
  - build
  - chore
  - devops
  - docs
  - env
  - feat
  - fix
  - lint
  - perf
  - refactor
  - repo
  - revert
  - style
  - test
scopes:
  - deps
  - core
