{
  name: Coverage,
  on: [push, pull_request],
  jobs:
    {
      codecov:
        {
          name: Codecov,
          runs-on: ubuntu-latest,
          steps:
            [
              { uses: actions/checkout@v2 },
              { uses: actions/setup-node@v1, with: { node-version: 14 } },
              { run: yarn install-ci },
              { run: yarn coverage-ci },
              { run: 'bash <(curl -s https://codecov.io/bash)' },
            ],
        },
      codacy:
        {
          name: Codacy,
          runs-on: ubuntu-latest,
          steps:
            [
              { uses: actions/checkout@v2 },
              { uses: actions/setup-node@v1, with: { node-version: 14 } },
              { run: yarn install-ci },
              { run: yarn coverage-ci },
              {
                uses: codacy/codacy-coverage-reporter-action@master,
                with: { project-token: '${{ secrets.CODACY_PROJECT_TOKEN }}' },
              },
            ],
        },
    },
}
