{
  name: Coverage,
  on: [push, pull_request],
  jobs:
    {
      coverage:
        {
          name: Collect Coverage,
          runs-on: ubuntu-latest,
          steps:
            [
              { uses: actions/checkout@v2 },
              { uses: actions/setup-node@v1, with: { node-version: 14 } },
              { run: yarn install-ci },
              { run: yarn coverage-ci },
              { run: 'bash <(curl -s https://codecov.io/bash)' },
            ],
        },
    },
}
